name: alloy-example

include:
  - ./grafana.yaml
  - ./databases.yaml

services:
  alloy:
    image: grafana/alloy:v1.5.1
    pull_policy: always
    profiles: ["alloy"]
    restart: on-failure
    volumes:
      - ./config/alloy:/etc/alloy
    environment:
      REMOTE_WRITE_HOST: mimir:9009
      LOKI_HOST: loki:3100
      TEMPO_HOST: tempo:4317
      PYROSCOPE_HOST: pyroscope:4040
      ALLOY_VERSION: 1.0.0
    depends_on:
      - mimir
      - loki
      # - tempo
      # - pyroscope
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental # Enable all functionality
    ports:
      - "12345:12345"

  # 5. OS 메트릭: Node Exporter (Alloy가 아님)
  node-exporter:
    image: prom/node-exporter:v1.8.1 # 버전은 명시되지 않아 최신 계열 사용
    container_name: node-exporter
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/host/root"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9100:9100"
    pid: host # ★ OS 메트릭 수집을 위해 호스트 PID 네임스페이스 필요
    volumes:
      # ★ OS 메트릭 수집을 위해 호스트 파일시스템 마운트 필요
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/host/root:ro"

  # # 6. 애플리케이션 메트릭: Demo App
  # demo-app:
  #   container_name: demo-app
  #   build: ./demo-app
  #   ports:
  #     - "8000:8000" # /metrics 포트
